# Generated by Django 5.2.1 on 2025-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_items', models.CharField(max_length=100)),
                ('price_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_create',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
